name: cactusclicker
author: lightPlugins
version: 0.1.0
main: io.lightplugins.cactusclicker.Light
api-version: 1.20
depend: []
softdepend: []
loadbefore: []
libraries: []
#  - org.mariadb.jdbc:mariadb-java-client:2.7.4
#  - com.zaxxer:HikariCP:5.1.0
commands:
  cc:
    description: The root command for lightEconomy overall
    aliases: [dummy]